### ISSUE TITLE
Missing compatibility with Java 17

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/jellydoc-maven-plugin#38]
The package `com.sun.javadoc.*` has been deprecated for removal since Java 9, in favor of `jdk.javadoc.doclet.*`, which was introduced in the same release. We're using the sun classes in `TagXMLDoclet` still:
https://github.com/jenkinsci/maven-jellydoc-plugin/blob/b175cdffa6e69fb1eddca77efd7b00cd194b84e4/maven-jellydoc-plugin/src/main/java/org/jvnet/maven/jellydoc/TagXMLDoclet.java#L18-L30
If I recall correctly, they have been removed in Java 12 or 13. Therefore, using tasks looking for `com.sun.javadoc.*`, are failing on Java 17.

Given, we require Java 11 as baseline, we can safely make use of the new doclet API and get a rid of the sun one, to ensure this plugin's functionality is warranted on modern Java versions too.

**Comment by basil** [comment]
> @NotMyFault added the [Good first issue](https://github.com/jenkinsci/maven-jellydoc-plugin/labels/Good%20first%20issue) label

Why would this be labelled as a good first issue? It seems like a terrible first issue to me due to the difficulty in testing the change.
